### ISSUE TITLE
Provide Swagger Documentation

### ISSUE THREAD

**Issue by junnipan** [NYUSquadO/orders#120]
**As a** developer
**I need** to add Swagger annotations to our service
**So that** we can document our API by using Flask-RESTX

**Details & Assumptions:** 
* The documentation API must be available at: BASEURL/apidocs/
* Add Swagger data models to document your API payloads
* Ensure that you Swagger docs work correctly and specify your data model so that others know what to send to your API

**Acceptance Criteria:**

```gherkin
Given the server is running
When the developer enter the endpoint of API documentation (BASEURL/apidocs)
Then the developer can see the Swagger documentation
```

**Comment by sandeep-nyu** [comment]
Duplicate
