### ISSUE TITLE
 Integrate Pull Requests with Orders Slack Channel

### ISSUE THREAD

**Issue by sandeep-nyu** [NYUSquadO/orders#56]
**As a** code reviewer and member of orders team
**I need** a Slack and Github integration
**So that** I  can get immediately notified about pull requests

**Details & Assumptions:** 
* Orders slack channel exists
* 

**Acceptance Criteria:**

```gherkin
Given slack is integrated with GitHub
When I create a pull request
Then I get immediately notified on Slack about the PR. 
```

**Comment by Xiaotong-Hu** [comment]
We can get the PR notification in the Slack channel now.
