### ISSUE TITLE
Implement simple UI for Order

### ISSUE THREAD

**Issue by junnipan** [NYUSquadO/orders#84]
**As a** User
**I need** a UI page for order
**So that** I can interact with my orders

**Details & Assumptions:** 
* Able to List all orders
* Able to Retrieve, Delete, Cancel an order
* Able to create and update order

**Acceptance Criteria:**

```gherkin
Given a valid input
When interact with the UI page
Then RESTful API will perform accordingly
```

**Comment by sandeep-nyu** [comment]
Will BDD tests for each of these functionalities be a part of this issue?

**Comment by junnipan** [comment]
> Will BDD tests for each of these functionalities be a part of this issue?

I think this issue is only about UI implementation.

**Comment by sandeep-nyu** [comment]
ok! How do we test the UI then in an automated manner? I think we should also write the corresponding BDD tests when we work on a specific UI functionality.

**Comment by junnipan** [comment]
> ok! How do we test the UI then in an automated manner? I think we should also write the corresponding BDD tests when we work on a specific UI functionality.

We are going to test it by using Behave, and I modified the Acceptance Criteria part of issue BDD test for List Items in order based on Prof's example. I think we should use detailed scenario and user behavior at that place.
